import type { NextPage } from 'next';
import Head from 'next/head';
import ContainerCentralizer from '../Components/Centralizer';

import { Box } from '../styles/pages/home';

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerCentralizer>
        <p>Testando</p>
      </ContainerCentralizer>
    </Box>
  );
};

export default Home;
