import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { BiSearch, BiBook } from 'react-icons/bi';
import { BsHeart, BsHeartFill } from 'react-icons/bs';
import { ImFilm } from 'react-icons/im';
import { SiBookstack } from 'react-icons/si';

import ContainerCentralizer from '../../Components/Centralizer';
import { Box } from '../../styles/pages/details';
import { api } from '../../utils/services';
import { CharacterProps } from '../../utils/types';

const Details: NextPage = () => {
  const route = useRouter();
  const pid: any = route.query.heroe;
  const [search, setSearch] = useState('');

  const [load, setLoad] = useState(true);
  const [favoritesHeroes, setFavoritesHeroes] = useState<number[]>([]);
  const [heroeDetails, setHeroeDetails] = useState<CharacterProps>();
  const [statusFavoriteHero, setStatusFavoriteHero] = useState(true);

  useEffect(() => {
    async function getCharacters() {
      const { data } = await api.get(`/characters/${pid}`);
      setHeroeDetails(data.data.results[0]);
    }
    const storage: number[] =
      localStorage.getItem('HEROE_FAV') == null
        ? ''
        : JSON.parse(localStorage.getItem('HEROE_FAV')!);

    setFavoritesHeroes(storage);
    getCharacters();
    setLoad(false);
  }, [pid]);

  function favoriteHeroeVerification() {
    const heroesStorage: number[] =
      localStorage.getItem('HEROE_FAV') == null
        ? ''
        : JSON.parse(localStorage.getItem('HEROE_FAV')!);

    if (!statusFavoriteHero == true) {
      const addHeroeStorage = [...heroesStorage, heroeDetails?.id];
      if (addHeroeStorage.length > 5) {
        return alert('Algo deu errado');
      } else {
        localStorage.setItem('HEROE_FAV', JSON.stringify(addHeroeStorage));
      }
    } else {
      const removeHeroeStorage = heroesStorage.filter(
        id => id !== heroeDetails?.id
      );
      localStorage.setItem('HEROE_FAV', JSON.stringify(removeHeroeStorage));
    }
  }

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerCentralizer>
        <div className="header">
          <div className="logoContainer">
            <Image src={'/img/marvel.png'} width={'110px'} height={'42px'} />
            <p className="logoComent">Search heros</p>
          </div>
          <div className="inputContainer">
            <BiSearch className="icon" />
            <input
              type={'text'}
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
          </div>
        </div>
        <div className="details">
          <div className="heroDetail">
            <div className="title">
              <h2>{heroeDetails?.name.toLocaleUpperCase()}</h2>
              <div
                className="icons"
                onClick={() => {
                  favoriteHeroeVerification();
                  setStatusFavoriteHero(!statusFavoriteHero);
                }}
              >
                {statusFavoriteHero == true ? <BsHeartFill /> : <BsHeart />}
              </div>
            </div>
            <div className="description">
              <p>{heroeDetails?.description}</p>
            </div>
            <div className="stats">
              <div className="comics">
                <h4>Quadrinhos</h4>
                <div className="numbers">
                  <SiBookstack className="icon" />
                  <p> {heroeDetails?.comics?.available}</p>
                </div>
              </div>
              <div className="comics">
                <h4>Séries</h4>
                <div className="numbers">
                  <ImFilm className="icon" />
                  <p> {heroeDetails?.series?.available}</p>
                </div>
              </div>
            </div>
            <div className="history">
              <h4>Último quadrinho:</h4>
            </div>
          </div>
          <div className="picture">
            {heroeDetails == undefined ? null : (
              <Image
                src={`${heroeDetails?.thumbnail.path}.${heroeDetails?.thumbnail.extension}`}
                width={500}
                height={500}
                style={{ borderBottom: '5px solid red' }}
              />
            )}
          </div>
        </div>
      </ContainerCentralizer>
    </Box>
  );
};

export default Details;
